### ISSUE TITLE
todo v0.1.0

### ISSUE THREAD

**Issue by oss6** [oss6/sakin#2]
- [x] Use streams for `getContent` in reader
- [x] Use 'smart generation'
- [x] CLI theme
- [x] Event system between modules and cli (for logging)
- [x] When removing content files, reflect the changes to the output directory
- [x] Automatic generation when previewing
- [x] Sort articles by date
- [x] GitHub publishing: add support for project pages
- [x] Themes
- [x] Support categories/tags
- [x] Fix social buttons
- [x] Order articles in category view
- [x] Delete a category from an article
- [x] Date filtering in template
- [x] Pagination
- [x] Disqus
- [x] Custom homepage
